### ISSUE TITLE
No working CI for this repo

### ISSUE THREAD

**Issue by jhoblitt** [Puppet-Finland/puppet-ipa#42]
It appears that the travis configuration is dead.  Perhaps this repo could be migrated to github actions?

**Comment by mattock** [comment]
I agree. Have you done GHA with Puppet, or have links to Puppet modules that do it? I did some experimentation with GHA using these actions:

* https://github.com/marketplace/actions/action-pdk-test-unit
* https://github.com/marketplace/actions/action-pdk-validate

However, at least the pdk-test-unit thing failed miserably, something wrong with the Docker image I think.

**Comment by jhoblitt** [comment]
Yes, I am familiar with testing puppet mods with gha. My preference is to use the voxpupuli plumbing.   Would a PR for voxpupuli modulesync be considered?

**Comment by mattock** [comment]
Yes, I would love to have a working integration here. I could then copy it over to the other important modules I maintain.

**Comment by jhoblitt** [comment]
Implemented.
